spring:
  application:
    name: distributed-discovery
server:
  port: 53000
eureka:
  #server:
    #enable-self-preservation: false
    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护
    #eviction-interval-timer-in-ms: 10000
    #should-use-ReadOnlyResponseCache: true
  client:
    register-with-eureka: false #false 表示不作为一个客户端注册到注册中心
    fetch-registry: false       #true 表示可以启动，但报异常
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
